[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:laravel-server]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisor/laravel-server.log
stderr_logfile=/var/log/supervisor/laravel-server.err.log

# Age mikhay Queue Worker ham dashte bashi in ro ezafe kon:
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
user=root
stopasgroup=true
killasgroup=true

# Age mikhay Queue Worker ham dashte bashi in ro ezafe kon:
[program:laravel-worker-market]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=market
autostart=true
autorestart=true
user=root
stopasgroup=true
killasgroup=true


[program:scheduler]
command=php artisan schedule:work
directory=/var/www
autostart=true
autorestart=true

[program:reverb]
command=php artisan reverb:start --host=0.0.0.0 --port=8081
directory=/var/www
autostart=true
autorestart=true
